# Generated by Django 4.2 on 2023-04-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wallet_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('destination', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('preimage', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('rider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wallet_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
